import type { Metadata } from "next";
import { Geist, Geist_Mono, Parisienne, Mona_Sans } from "next/font/google";
import "./globals.css";
import { ReactLenis } from '@/utils/lenis'

const monaSans = Mona_Sans({
    variable: "--font-mona-sans",
    subsets: ["latin"],
});


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const parisienne = Parisienne({
    variable: "--font-parisienne",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ReactLenis root>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} ${parisienne.variable} ${monaSans.variable} antialiased`}
                >
                    {children}
                </body> 
            </ReactLenis>
        </html>
    );
}
